### ISSUE TITLE
How to Train , any instruction and steps?  essential option to change in tranl.py

### ISSUE THREAD

**Issue by zdxpan** [AMorporkian/T2IAdapter-SDXL-Diffusers#2]
really thanks the repo, i getting trouble with how to trainning in coAdapter mode ,given 
`https://github.com/TencentARC/T2I-Adapter/blob/main/docs/coadapter.md`
it shown mult adapter can enhance the quality

**Comment by zdxpan** [comment]
how to use the segment  adapter  which only had 1 channel, and get error  chanel require 192, but input channel is  64

**Comment by AMorporkian** [comment]
It defaults to 1 channel for grayscale, you'll need to update the adapter
type in the initialization code to use 3 for RGB
